# -*- coding: utf-8 -*-

"""
Vizabull aggregation / mappings / weightings definitions

"""


def inverse_map(groupings: dict) -> dict:
    return dict((value, key) for key in groupings for value in groupings[key])


# Create region lists
default_us_region_groupings = {
    "East North Central": ["US-IL", "US-IN", "US-MI", "US-OH", "US-WI"],
    "East South Central": ["US-AL", "US-KY", "US-MS", "US-TN"],
    "Mid Atlantic": ["US-NJ", "US-NY", "US-PA"],
    "Mountain": ["US-AZ", "US-CO", "US-ID", "US-MT", "US-NM", "US-NV", "US-UT", "US-WY"],
    "New England": ["US-CT", "US-MA", "US-ME", "US-NH", "US-RI", "US-VT"],
    "Pacific": ["US-AK", "US-CA", "US-HI", "US-OR", "US-WA"],
    "South Atlantic": ["US-DC", "US-DE", "US-FL", "US-GA", "US-NC", "US-MD",  "US-SC", "US-VA", "US-WV"],
    "West North Central": ["US-IA", "US-KS", "US-MN", "US-MO", "US-ND", "US-NE", "US-SD"],
    "West South Central": ["US-AR", "US-LA", "US-OK", "US-TX"],
}

regions_to_states = default_us_region_groupings
states_to_regions = inverse_map(regions_to_states)
all_state_airport_mappings = {
    "US-AK": ["PAMR"],
    "US-AL": ["KBFM", "KBHM", "KHUA", "KMGM", "KTCL"],
    "US-AR": ["KFSM", "KFYV", "KLIT", "KLRF"],
    "US-AZ": ["KDMA", "KLUF", "KNYL", "KPRC"],
    "US-CA": [
        "KAPC",
        "KBFL",
        "KCIC",
        "KEED",
        "KFAT",
        "KIPL",
        "KLAX",
        "KMCC",
        "KMCE",
        "KMOD",
        "KMYV",
        "KNKX",
        "KOXR",
        "KRAL",
        "KRDD",
        "KSBP",
        "KSCK",
        "KSFO",
        "KSJC",
        "KSMX",
        "KSNS",
        "KSTS",
        "KTRK",
        "KTVL",
        "KVIS",
        "KWVI",
    ],
    "US-CO": ["KBDU", "KCOS", "KDEN", "KFNL", "KGXY", "KSBS"],
    "US-CT": ["KGON", "KHFD", "KHVN"],
    "US-DC": ["KDCA"],
    "US-DE": ["KDOV"],
    "US-FL": [
        "KCEW",
        "KDAB",
        "KFMY",
        "KGNV",
        "KLAL",
        "KMCF",
        "KMCO",
        "KMIA",
        "KMKY",
        "KMLB",
        "KOCF",
        "KPAM",
        "KPGD",
        "KPNS",
        "KSRQ",
        "KSUA",
        "KTLH",
    ],
    "US-GA": ["KAGS", "KAHN", "KFTY", "KGVL", "KMCN", "KSAV", "KWRB"],
    "US-HI": ["PHNL"],
    "US-IA": ["KALO", "KBRL", "KCID", "KDSM", "KIOW", "KSUX"],
    "US-ID": ["KBOI"],
    "US-IL": ["KCMI", "KCPS", "KDPA", "KMLI", "KPIA", "KRFD", "KSPI"],
    "US-IN": [
        "KBMG",
        "KEKM",
        "KEVV",
        "KEYE",
        "KFWA",
        "KHNB",
        "KHUF",
        "KLAF",
        "KSBN",
    ],
    "US-KS": ["KICT", "KTOP"],
    "US-KY": ["KBWG", "KLEX", "KLOU"],
    "US-LA": ["KBTR", "KHUM", "KLCH", "KLFT", "KMLU", "KMSY", "KSHV"],
    "US-MA": ["KBOS", "KCEF", "KHYA", "KORH"],
    "US-MD": ["KHGR", "KSBY"],
    "US-ME": ["KPWM"],
    "US-MI": ["KARB", "KAZO", "KDET", "KFNT", "KGRR", "KLAN", "KMBS", "KMKG"],
    "US-MN": ["KDLH", "KMSP", "KRST", "KSGS", "KSTC"],
    "US-MO": ["KCOU", "KJLN", "KMCI", "KSGF", "KSUS"],
    # "US-MS": ["KGLH", "KGPT"],
    "US-MS": ["KGPT"],
    "US-MT": ["KBIL"],
    "US-NC": [
        "KAVL",
        "KCLT",
        "KFAY",
        "KGSO",
        "KHKY",
        "KILM",
        "KINT",
        "KIXA",
        "KPGV",
        "KRDU",
    ],
    "US-ND": ["KFAR"],
    "US-NE": ["KOMA", "KLNK"],
    "US-NH": ["KAFN", "KCWN", "KMHT"],
    "US-NJ": ["KEWR", "KTTN", "KACY"],
    "US-NM": ["KABQ", "KLRU"],
    "US-NV": ["KLAS", "KRNO"],
    "US-NY": [
        "KALB",
        "KBGM",
        "KBUF",
        "KHPN",
        "KJFK",
        "KPOU",
        "KRME",
        "KROC",
        "KSYR",
    ],
    "US-OH": [
        "KAKR",
        "KBKL",
        "KCAK",
        "KCGF",
        "KCMH",
        "KEDJ",
        "KFFO",
        "KLUK",
        "KOSU",
        "KTDZ",
        "KYNG",
    ],
    "US-OK": ["KOKC", "KTUL"],
    "US-OR": ["KBDN", "KEUG", "KMFR", "KPDX", "KSLE"],
    "US-PA": [
        "KABE",
        "KAGC",
        "KAVP",
        "KCXY",
        "KERI",
        "KLNS",
        "KMPO",
        "KPHL",
        "KRDG",
        "KTHV",
    ],
    "US-RI": ["KPVD"],
    "US-SC": ["KFLO", "KHXD", "KJZI", "KMYR", "KSPA"],
    "US-SD": ["KFSD"],
    "US-TN": ["KBNA", "KCHA", "KCKV", "KMEM", "KTRI", "KTYS"],
    "US-TX": [
        "KABI",
        "KACT",
        "KAMA",
        "KAUS",
        "KBIF",
        "KBPT",
        "KBRO",
        "KCLL",
        "KCRP",
        "KDAL",
        "KEFD",
        "KGGG",
        "KHLR",
        "KLBB",
        "KLRD",
        "KMDD",
        "KMFE",
        "KRND",
        "KTYR",
    ],
    "US-UT": ["K36U", "KHIF", "KPVU", "KSLC"],
    "US-VA": ["KBCB", "KCHO", "KHSP", "KLYH", "KNTU", "KRIC", "KROA"],
    # "US-VT": ["KBRL"], # incorrectly mapped versus DB / actual weather station location
    "US-VT": ["KDDH"],
    "US-WA": ["KBFI", "KBLI", "KGEG", "KOLM", "KPSC", "KPWT", "KYKM"],
    "US-WI": ["KATW", "KGRB", "KMKE", "KMSN", "KOSH", "KRAC"],
    "US-WV": ["KHTS"],
    "US-WY": ['KJAC'],
}

default_state_airport_mappings = {"US-AK": ['PAMR'],
                                  "US-AL": ['KBHM', 'KHUA', 'KBFM', 'KMGM', 'KTCL'],
                                  "US-AR": ['KLIT', 'KFYV', 'KFSM'],
                                  "US-AZ": ['KLUF', 'KDMA'],
                                  "US-CA": ['KLAX', 'KSFO', 'KRAL', 'KNKX', 'KMCC', 'KSJC'],
                                  "US-CO": ['KDEN', 'KCOS', 'KFNL', 'KBDU', 'KGXY'],
                                  # "US-CT": ['KHFD', 'KHPN', 'KHVN', 'KGON'],
                                  "US-CT": ['KHFD', 'KHVN', 'KGON'],
                                  "US-DC": ['KDCA'],
                                  "US-DE": ['KDOV'],
                                  # "US-FL": ['KMIA', 'KMCF', 'KMCO', 'KLRF'],
                                  "US-FL": ['KMIA', 'KMCF', 'KMCO'],
                                  "US-GA": ['KFTY', 'KAGS', 'KSAV'],
                                  "US-HI": ['PHNL'],
                                  # "US-IA": ['KDSM', 'KMLI', 'KCID', 'KALO', 'KSUX'],
                                  "US-IA": ['KDSM', 'KCID', 'KALO', 'KSUX'],
                                  "US-ID": ['KBOI'],
                                  "US-IL": ['KDPA'],
                                  "US-IN": ['KEYE', 'KFWA', 'KSBN', 'KEVV', 'KLAF'],
                                  "US-KS": ['KICT', 'KTOP'],
                                  "US-KY": ['KLOU', 'KLEX', 'KBWG'],
                                  "US-LA": ['KMSY', 'KBTR', 'KLFT', 'KSHV', 'KHUM', 'KLCH'],
                                  "US-MA": ['KBOS', 'KORH', 'KCEF'],
                                  "US-MD": ['KSBY', 'KHGR'],
                                  "US-ME": ['KPWM'],
                                  "US-MI": ['KDET', 'KGRR', 'KLAN', 'KFNT'],
                                  "US-MN": ['KMSP', 'KDLH'],
                                  # "US-MO": ['KCPS', 'KMCI', 'KSGF'],
                                  "US-MO": ['KMCI', 'KSGF'],
                                  "US-MS": ['KGPT'],
                                  "US-MT": ['KBIL'],
                                  # "US-NC": ['KCLT', 'KRDU', 'KGSO', 'KINT', 'KAVL', 'KCRW'],
                                  "US-NC": ['KCLT', 'KRDU', 'KGSO', 'KINT', 'KAVL'],
                                  "US-ND": ['KFAR'],
                                  "US-NE": ['KOMA', 'KLNK'],
                                  "US-NH": ['KMHT'],
                                  "US-NJ": ['KEWR', 'KTTN', 'KACY'],
                                  "US-NM": ['KABQ', 'KLRU'],
                                  "US-NV": ['KLAS', 'KRNO'],
                                  "US-NY": ['KJFK', 'KBUF', 'KROC', 'KALB'],
                                  "US-OH": ['KLUK', 'KBKL', 'KOSU', 'KFFO', 'KAKR', 'KTDZ'],
                                  "US-OK": ['KOKC', 'KTUL'],
                                  "US-OR": ['KPDX', 'KSLE', 'KEUG', 'KMFR'],
                                  "US-PA": ['KPHL', 'KAGC', 'KABE'],
                                  "US-RI": ['KPVD'],
                                  # "US-SC": ['KGLH', 'KCOU', 'KJZI', 'KMYR', 'KSPA', 'KHXD', 'KFLO'],
                                  "US-SC": ['KJZI', 'KMYR', 'KSPA', 'KHXD', 'KFLO'],
                                  "US-SD": ['KFSD'],
                                  "US-TN": ['KBNA', 'KMEM', 'KTYS', 'KCHA', 'KTRI', 'KCKV'],
                                  "US-TX": ['KDAL', 'KEFD', 'KRND', 'KAUS'],
                                  "US-UT": ['KSLC', 'KHIF', 'KPVU'],
                                  # "US-VA": ['KNTU', 'KRIC', 'KDCA', 'KROA'],
                                  "US-VA": ['KNTU', 'KRIC', 'KROA'],
                                  # "US-VT": ['KBRL'], # incorrectly mapped
                                  "US-VT": ['KDDH'],
                                  "US-WA": ['KBFI', 'KGEG'],
                                  "US-WI": ['KMKE', 'KMSN', 'KGRB', 'KATW', 'KRAC', 'KOSH'],
                                  "US-WV": ['KHTS'],
                                  "US-WY": ['KJAC'],
                                  }

states_to_airports = default_state_airport_mappings
airports_to_states = inverse_map(states_to_airports)

airport_to_region = {}
for k in airports_to_states.keys():
    airport_to_region[k] = states_to_regions[airports_to_states[k]]
all_analysed_tickers = [
    "HOME",
    "HOG",
    "HD",
    # "LOW",
    "BLDR",
    "TTC",
    "SMG",
    "SITE",
    "TSC",
    "SHW",
    "URI",
    "KMX",
    "COLM",
    "GOLF",
    "ELY",
    "WSO",
    "AAP",
    "ORLY",
    "AZO",
    "MNRO",
    "GT",
    "MGDDY",
    "CTB",
    "CENT",
    "WMT",
    "TGT",
    "BIG",
    "DKS",
    # "CAB",
    "VSTO",
    "ROST",
    "TJX",
    "BURL",
    "KSS",
    "M",
    "JWN",
    "FIVE",
    # "HBAY",
]
